# Generated by Django 4.2.4 on 2024-07-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=25)),
                (
                    "course",
                    models.CharField(
                        choices=[("python", "python"), ("java", "java")], max_length=25
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
